// Code generated by protoc-gen-go. DO NOT EDIT.
// source: domain.proto

package persistence

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LineItem struct {
	ProductId            string   `protobuf:"bytes,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity             int32    `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LineItem) Reset()         { *m = LineItem{} }
func (m *LineItem) String() string { return proto.CompactTextString(m) }
func (*LineItem) ProtoMessage()    {}
func (*LineItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_73e6234e76dbdb84, []int{0}
}

func (m *LineItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineItem.Unmarshal(m, b)
}
func (m *LineItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineItem.Marshal(b, m, deterministic)
}
func (m *LineItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineItem.Merge(m, src)
}
func (m *LineItem) XXX_Size() int {
	return xxx_messageInfo_LineItem.Size(m)
}
func (m *LineItem) XXX_DiscardUnknown() {
	xxx_messageInfo_LineItem.DiscardUnknown(m)
}

var xxx_messageInfo_LineItem proto.InternalMessageInfo

func (m *LineItem) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *LineItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LineItem) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

// The item added event.
type ItemAdded struct {
	Item                 *LineItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ItemAdded) Reset()         { *m = ItemAdded{} }
func (m *ItemAdded) String() string { return proto.CompactTextString(m) }
func (*ItemAdded) ProtoMessage()    {}
func (*ItemAdded) Descriptor() ([]byte, []int) {
	return fileDescriptor_73e6234e76dbdb84, []int{1}
}

func (m *ItemAdded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemAdded.Unmarshal(m, b)
}
func (m *ItemAdded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemAdded.Marshal(b, m, deterministic)
}
func (m *ItemAdded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemAdded.Merge(m, src)
}
func (m *ItemAdded) XXX_Size() int {
	return xxx_messageInfo_ItemAdded.Size(m)
}
func (m *ItemAdded) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemAdded.DiscardUnknown(m)
}

var xxx_messageInfo_ItemAdded proto.InternalMessageInfo

func (m *ItemAdded) GetItem() *LineItem {
	if m != nil {
		return m.Item
	}
	return nil
}

// The item removed event.
type ItemRemoved struct {
	ProductId            string   `protobuf:"bytes,1,opt,name=productId,proto3" json:"productId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemRemoved) Reset()         { *m = ItemRemoved{} }
func (m *ItemRemoved) String() string { return proto.CompactTextString(m) }
func (*ItemRemoved) ProtoMessage()    {}
func (*ItemRemoved) Descriptor() ([]byte, []int) {
	return fileDescriptor_73e6234e76dbdb84, []int{2}
}

func (m *ItemRemoved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemRemoved.Unmarshal(m, b)
}
func (m *ItemRemoved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemRemoved.Marshal(b, m, deterministic)
}
func (m *ItemRemoved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemRemoved.Merge(m, src)
}
func (m *ItemRemoved) XXX_Size() int {
	return xxx_messageInfo_ItemRemoved.Size(m)
}
func (m *ItemRemoved) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemRemoved.DiscardUnknown(m)
}

var xxx_messageInfo_ItemRemoved proto.InternalMessageInfo

func (m *ItemRemoved) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

// The shopping cart state.
type Cart struct {
	Items                []*LineItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Cart) Reset()         { *m = Cart{} }
func (m *Cart) String() string { return proto.CompactTextString(m) }
func (*Cart) ProtoMessage()    {}
func (*Cart) Descriptor() ([]byte, []int) {
	return fileDescriptor_73e6234e76dbdb84, []int{3}
}

func (m *Cart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cart.Unmarshal(m, b)
}
func (m *Cart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cart.Marshal(b, m, deterministic)
}
func (m *Cart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cart.Merge(m, src)
}
func (m *Cart) XXX_Size() int {
	return xxx_messageInfo_Cart.Size(m)
}
func (m *Cart) XXX_DiscardUnknown() {
	xxx_messageInfo_Cart.DiscardUnknown(m)
}

var xxx_messageInfo_Cart proto.InternalMessageInfo

func (m *Cart) GetItems() []*LineItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*LineItem)(nil), "com.example.shoppingcart.persistence.LineItem")
	proto.RegisterType((*ItemAdded)(nil), "com.example.shoppingcart.persistence.ItemAdded")
	proto.RegisterType((*ItemRemoved)(nil), "com.example.shoppingcart.persistence.ItemRemoved")
	proto.RegisterType((*Cart)(nil), "com.example.shoppingcart.persistence.Cart")
}

func init() { proto.RegisterFile("domain.proto", fileDescriptor_73e6234e76dbdb84) }

var fileDescriptor_73e6234e76dbdb84 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x3f, 0x4b, 0x04, 0x31,
	0x10, 0xc5, 0x89, 0xb7, 0x27, 0xb7, 0xb3, 0xda, 0xa4, 0x0a, 0x62, 0xb1, 0x04, 0x8b, 0x03, 0x21,
	0x85, 0x7e, 0x02, 0x4f, 0x9b, 0x85, 0x05, 0x61, 0x2b, 0xb1, 0x8b, 0xc9, 0xa0, 0x01, 0xf3, 0xc7,
	0x64, 0x56, 0xf4, 0xdb, 0xcb, 0x46, 0xfc, 0x53, 0x89, 0x5c, 0x37, 0x6f, 0x1e, 0xef, 0xcd, 0x8f,
	0x81, 0x23, 0x1b, 0xbd, 0x76, 0x41, 0xa5, 0x1c, 0x29, 0xf2, 0x33, 0x13, 0xbd, 0xc2, 0x37, 0xed,
	0xd3, 0x33, 0xaa, 0xf2, 0x14, 0x53, 0x72, 0xe1, 0xd1, 0xe8, 0x4c, 0x2a, 0x61, 0x2e, 0xae, 0x10,
	0x06, 0x83, 0xf2, 0x0e, 0x36, 0xa3, 0x0b, 0x38, 0x10, 0x7a, 0x7e, 0x0a, 0x6d, 0xca, 0xd1, 0xce,
	0x86, 0x06, 0x2b, 0x58, 0xcf, 0xb6, 0xed, 0xf4, 0xb3, 0xe0, 0x1c, 0x9a, 0xa0, 0x3d, 0x8a, 0x83,
	0x6a, 0xd4, 0x99, 0x9f, 0xc0, 0xe6, 0x65, 0xd6, 0x81, 0x1c, 0xbd, 0x8b, 0x55, 0xcf, 0xb6, 0xeb,
	0xe9, 0x5b, 0xcb, 0x5b, 0x68, 0x97, 0xd6, 0x2b, 0x6b, 0xd1, 0xf2, 0x1d, 0x34, 0x8e, 0xd0, 0xd7,
	0xd6, 0xee, 0x42, 0xa9, 0xff, 0xb0, 0xa9, 0x2f, 0xb0, 0xa9, 0x66, 0xe5, 0x39, 0x74, 0x55, 0xa1,
	0x8f, 0xaf, 0x68, 0xff, 0xa6, 0x95, 0x23, 0x34, 0xd7, 0x3a, 0x13, 0xbf, 0x81, 0xf5, 0x12, 0x2e,
	0x82, 0xf5, 0xab, 0x3d, 0x2e, 0x7f, 0x86, 0x77, 0xc7, 0xf7, 0xdd, 0x2f, 0xfb, 0xe1, 0xb0, 0x7e,
	0xf8, 0xf2, 0x23, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xe9, 0xbb, 0x2b, 0x71, 0x01, 0x00, 0x00,
}
